name: Deploy Dividends Tracker Frontend
on:
  push:
    branches:
      - 'master'

env:
  NODE_VERSION: '20.5.1'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci

      - name: Build Astro
        env:
          VITE_URL_BASE: ${{secrets.VITE_URL_BASE}}
          VITE_ASSETS_URL_BASE: ${{secrets.VITE_ASSETS_URL_BASE}}
          ALPHA_VANTAGE_API_TOKEN: ${{secrets.ALPHA_VANTAGE_API_TOKEN}}
          ALPHA_VANTAGE_API_URL: ${{secrets.ALPHA_VANTAGE_API_URL}}
          FINNHUB_API_TOKEN: ${{secrets.FINNHUB_API_TOKEN}}
          FINNHUB_API_URL: ${{secrets.FINNHUB_API_URL}}
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: div-trak
          entrypoint: server/entry.mjs
          root: dist
